CREATE TABLE "merchant" (
  id CHAR(26) PRIMARY KEY,

  name VARCHAR(50) NOT NULL,
  dbName VARCHAR(50) NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL 
);
